/**
 * Vault Initializer - Sets up Obsidian vault structure for Thalamus AI
 */

import * as path from 'path';
import * as fs from 'fs';

export class VaultInitializer {
  private vaultDir: string;

  constructor(vaultDir?: string) {
    const home = process.env.HOME || process.env.USERPROFILE || '/tmp';
    this.vaultDir = vaultDir || path.join(home, 'Documents', 'Obsidian Vault');
  }

  async init(): Promise<void> {
    console.log(`Initializing vault at: ${this.vaultDir}`);

    // Create main directories
    const dirs = [
      '06-PROJECTS',
      'Daily Notes',
      '_templates',
      '99-MIRROR'
    ];

    for (const dir of dirs) {
      const fullPath = path.join(this.vaultDir, dir);
      if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
        console.log(`  Created: ${dir}`);
      }
    }

    // Create templates
    await this.createTemplates();

    // Create index files
    await this.createIndices();

    console.log('Vault initialization complete');
  }

  private async createTemplates(): Promise<void> {
    const templatesDir = path.join(this.vaultDir, '_templates');

    // Daily note template
    const dailyTemplate = `# {{date:YYYY-MM-DD}}

## AI Builds

## Meetings

## Notes

## Tasks
- [ ] 

---
Created: {{date:YYYY-MM-DD HH:mm}}
`;

    // Project note template
    const projectTemplate = `# {{title}}

## Overview

## Architecture

## Builds

## Tasks
- [ ] 

## Notes

---
Project: {{title}}
Created: {{date:YYYY-MM-DD}}
`;

    // Evidence note template
    const evidenceTemplate = `# {{title}}

## Metadata
- **Intent ID**: 
- **Status**: 
- **Date**: {{date:YYYY-MM-DD}}

## Artifacts

## Test Results

## Links

---
*Synced by Thalamus AI*
`;

    fs.writeFileSync(path.join(templatesDir, 'Daily Note.md'), dailyTemplate);
    fs.writeFileSync(path.join(templatesDir, 'Project.md'), projectTemplate);
    fs.writeFileSync(path.join(templatesDir, 'Evidence.md'), evidenceTemplate);

    console.log('  Created: templates');
  }

  private async createIndices(): Promise<void> {
    // Master project index
    const masterIndex = `# Projects Master Index

This index is automatically updated by Thalamus AI when new builds are completed.

## Active Projects

---
*Auto-generated by Thalamus AI*
`;

    fs.writeFileSync(
      path.join(this.vaultDir, '06-PROJECTS', '_Master Index.md'),
      masterIndex
    );

    console.log('  Created: indices');
  }
}
